name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Runner / Fix Repo Permissions
      run: |
        sudo chown -R $USER:$USER /home/github/actions-runner/_work/stayConnected-React/
        sudo chmod -R u+rwX /home/github/actions-runner/_work/stayConnected-React/

    - uses: actions/checkout@v4
    - name: Runner / Docker Image Build
      run: |
        docker compose build

    - name: Runner / Check Containers and Clean Up
      run: |
        docker compose down &&
        docker compose up -d &&
        docker image prune -af

    - name: Prod / Deploy
      run: |
        ssh -oStrictHostKeyChecking=no root@app01.prod.stayconnected.lol "
        cd ~/stayConnected-React/ \
        && git pull \
        && docker compose build \
        && docker compose down \
        && docker compose up -d \
        && docker image prune -af"
